### ISSUE TITLE
Thanks for this amazing work!

### ISSUE THREAD

**Issue by TattAIV2** [ostris/ai-toolkit#1]
The adaptations you made here are remarkable!. thanks for sharing this work!.
Do you have any plans to migrate the slider/extraction work for SDXL loras as well?

**Comment by jaretburkett** [comment]
Thank you. I have been working non stop on a migration to SDXL since it was released. I have had some random luck with it, but for the most part it does not work correctly. There is a lot of weird stuff going on with SDXL. I am honestly about to give up on it in general.
