### ISSUE TITLE
How is the flux schenell trainig adaptor trained? 

### ISSUE THREAD

**Issue by brappier** [ostris/ai-toolkit#104]
On what data did you train it on? 
DId you train it againt the flux.1 dev outputs?

**Comment by jaretburkett** [comment]
Thousands of schnell generated images. The goal was to not teach it anything other than decompression.

**Comment by brappier** [comment]
was it like 10k or 100k?? and how many iterations and batch size did you train it on? is the adaptor just a lora with 32 dim?

hmm that is a neat idea. i am curious, did it improve the quality of schnell generations in general?

i was thinking we should create a communtiy adaptor for schnell which makes it as good as dev. We can collect really high quality images, use LLave to annotate them ( like PixArt did ) and train schnell on a lot of iterations. community can fund the GPUs on runpod.

**Comment by brappier** [comment]
@jaretburkett

**Comment by affibox** [comment]
for some reason i was using the trainer in runpod and this adapto only produces bad images full of noise and grains
