### ISSUE TITLE
what is the lowest vram i can train flux lora?

### ISSUE THREAD

**Issue by brappier** [ostris/ai-toolkit#105]

**Comment by jaretburkett** [comment]
Currently 24GB

**Comment by brappier** [comment]
i was reading on reddit that kohya_ss is supporting 12GB vram. what magic they did which you did not?

**Comment by brappier** [comment]
@jaretburkett

**Comment by jaretburkett** [comment]
Probably text encoder embedding caching and 4bit quantization.

**Comment by brappier** [comment]
@jaretburkett  when are you doing all that?

**Comment by jaretburkett** [comment]
It is not planned at this time. Please keep issues for bugs only, and move general discussions to the discord.

**Comment by brappier** [comment]
ok i will move to discord. but do this fast. asap. im from china, your code is very popular here. cant say the name, but big companies using it for actual products

**Comment by brappier** [comment]
@jaretburkett
