### ISSUE TITLE
lora slider, is there a way to stop and resume?

### ISSUE THREAD

**Issue by igobymatthew** [ostris/ai-toolkit#11]
lora slider, is there a way to stop and resume for people that have slow gpus?

**Comment by FoundSol** [comment]
Using powershell terminal(assuming that you're using windows), press ctrl+c to stop the training, then when you want to resume, just re-type the code used initially(python run.py YourTemplate.yml). The toolkit save a metadata from training then you can start from where you stop. I've not tested this function deeply, but seems to work pretty fine. Remember to try this function before letting your concepts training for hours. A message like: 
'''Found step <NumberOfSteps> in metadata, starting from there''' must be shown if is resuming the training.

**Comment by jaretburkett** [comment]
Yes as @FoundSol mentioned, it it will auto resume if it finds a a saving step in the training folder. I do not save the state of the optimizer currently, but for general LoRA training, it is not really necessary (in my opinion)
