### ISSUE TITLE
linear_timesteps: true doesn't work in Google Colab

### ISSUE THREAD

**Issue by ingl6rious** [ostris/ai-toolkit#114]
## This is for bugs only

Did you already ask [in the discord](https://discord.com/invite/nuR9zZ2nsh)?

Yes

You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.com/invite/nuR9zZ2nsh)?

Yes

## Describe the bug

I want to use linear timestamps for vell curved weighting training in GoogleColab, but I can't get it running. Look:
```
('train', OrderedDict([
('batch_size', 1),
('steps', 4000),  # total number of steps to train 500 - 4000 is a good range
('gradient_accumulation_steps', 1),
('train_unet', True),
('train_text_encoder', False),  # probably won't work with flux
('content_or_style', 'balanced'),  # content, style, balanced
('gradient_checkpointing', True),  # need the on unless you have a ton of vram
('noise_scheduler', 'flowmatch'),  # for training only
('optimizer', 'adamw8bit'),
('lr', 4e-4),
linear_timesteps: true
```

What should i do?

**Comment by martintomov** [comment]
Your syntax is wrong, you can see the clear difference between linear_timestamps and all lines above it.

This is how you should do it:
```
(...)
('lr', 4e-4),

# uncomment this to skip the pre training sample
# ('skip_first_sample', True),

# uncomment to completely disable sampling
# ('disable_sampling', True),

# uncomment to use new vell curved weighting. Experimental but may produce better results
# ('linear_timesteps', True),
```

**Comment by ingl6rious** [comment]
works now
