### ISSUE TITLE
How to use the trained lora with diffuser or python code, without comfyui

### ISSUE THREAD

**Issue by WM-Wu** [ostris/ai-toolkit#122]
I  had train my own lora and got the safetensors. but i don't know how to use it in py code. Can someone give me an example? Thanks!

**Comment by martintomov** [comment]
upload it to hugging face and then click `Use this model > Diffusers`

you'll get something like this:

```
from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("black-forest-labs/FLUX.1-dev")
pipeline.load_lora_weights("username/lora")
