### ISSUE TITLE
Fine tuned FLUX-DEV successfully 

### ISSUE THREAD

**Issue by tzktok** [ostris/ai-toolkit#129]
Thx to the team...i have successfully finetuned  FLUX-DEV in RTX 4090 24Gb in lora rank 32 for 2000steps..which took 2hrs apprx..

![Screenshot (22)](https://github.com/user-attachments/assets/7c119bef-2742-4972-a8ed-15026fb583f6)

**Comment by n00mkrad** [comment]
Okay? Then close this issue.

**Comment by tabbietablet** [comment]
How did you change it to rank 32?

**Comment by tzktok** [comment]
> How did you change it to rank 32?

edit the config.yaml

**Comment by martintomov** [comment]
issues are only for bugs, please close this
