### ISSUE TITLE
[Feature] Compel support

### ISSUE THREAD

**Issue by DenisSergeevitch** [ostris/ai-toolkit#13]
Hi, I tested your Lora slider Colab, and it works great. Thank you for this project!

During testing, I found that for a precise slider, it is best for the --m +10 and --m -10 prompts to be as close visually as possible, i.e. _"sunny day, sepia photo"_ vs _"sunny day, modern photo"_. However, on the default prompt engineering level, each prompt produced drastically different results, even with a fixed seed, which affects the precise results of the Lora slider during the inference. 

Would it be possible for you to take into account the possibility of integrating the [Complel](https://github.com/damian0815/compel) library within your syntax?

It will help, for example, to do prompts like:
_"(sunny day:1.3), (sepia photo:0.3)"_ vs _"(sunny day:1.3), (modern photo:0.3)"_ 
Almost identical images on both positive and negative ends will help to do even more precise Lora sliders. 

Anyway, thank you for your work and really easy-to-use colab. Amazing work!

**Comment by jaretburkett** [comment]
It should be relatively easy to add. I just need to test how it will affect everything with some of the other features as they all use the same encoding functions. Probably not an issue, but ill look into it.

**Comment by DenisSergeevitch** [comment]
Amazing to hear, thank you!
