### ISSUE TITLE
[Question] So, no chance to train a Lora with a 4070 TI Super of 16Gb?😒

### ISSUE THREAD

**Issue by ZeroCool22** [ostris/ai-toolkit#132]
Maybe will be possible in the future or only ppl with 3090's & 4090's GPU's can train Loras for FLUX?

**Comment by EuphoricPenguin** [comment]
You can try, but it will probably fail. There is a low VRAM option that does something for you; I forgot to check what difference that made on my 3090.

**Comment by RalFingerLP** [comment]
> Maybe will be possible in the future or only ppl with 3090's & 4090's GPU's can train Loras for FLUX?

take a look at [fluxgym](https://github.com/cocktailpeanut/fluxgym/)

**Comment by RalFingerLP** [comment]
> Maybe will be possible in the future or only ppl with 3090's & 4090's GPU's can train Loras for FLUX?

Take a look at [fluxgym](https://github.com/cocktailpeanut/fluxgym/)

**Comment by ZeroCool22** [comment]
> > Maybe will be possible in the future or only ppl with 3090's & 4090's GPU's can train Loras for FLUX?
> 
> Take a look at [fluxgym](https://github.com/cocktailpeanut/fluxgym/)

![gif25](https://github.com/user-attachments/assets/37ccc2cc-207a-4d4f-82b3-f21faa31b90d)
