### ISSUE TITLE
Full flux finetuning produce 3 diffusers shards .safetensors unusable

### ISSUE THREAD

**Issue by BenDes21** [ostris/ai-toolkit#142]
Hi, I successfully full finetuned flux with ostris ai toolkit and I got theses 3 files at the end of the training ( diffusion model files ) :
diffusion_pytorch_model-00001-of-00003.safetensors
diffusion_pytorch_model-00002-of-00003.safetensors
diffusion_pytorch_model-00003-of-00003.safetensors

So I tried to merge/fusion them with this script for make a whole checkpoint usable for Forge :

```
import safetensors.torch

merge_state_dict ={}
files = ["name1.safetensors", "name2.safetensors"...] #file you want to be merged
merged_file = "merged_file.safetensors"
for file in files:
    load_files_dict = safetensors.torch.load_file(your.safetensors files)
merge_state_dict.update(load_files_dict)

# save
safetensors.torch.save_file(merge_state_dict, merged_file)
```

The issue is that I got ValueError: Failed to recognize model type! when I try to use the checkpoint with a1111 forge .safetensors generated from theses 3 " shards "

Im not even sure theses 3 " shards " supposed to be merged, if someone know how to use theses files for test my full fine-tuned flux checkpoint it's will be awesome, 

Thanks a lot

**Comment by doryashar** [comment]
any solution?

**Comment by BenDes21** [comment]
> any solution?

https://github.com/NotTheStallion/Re-shard_Safetensors

**Comment by int2char** [comment]
how to  full finetuned flux with ostris ai toolkit ?
