### ISSUE TITLE
"Please use torch.amp.autocast('cpu', args...) instead"

### ISSUE THREAD

**Issue by robertvoy** [ostris/ai-toolkit#150]
## This is for bugs only

Did you already ask [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

## Describe the bug

I am getting this error when training specific layers of a Flux LoRA:

:\ai-toolkit\venv\lib\site-packages\torch\utils\checkpoint.py:1399: FutureWarning: torch.cpu.amp.autocast(args...) is deprecated. Please use torch.amp.autocast('cpu', args...) instead.
  with device_autocast_ctx, torch.cpu.amp.autocast(**cpu_autocast_kwargs), recompute_context:  # type: ignore[attr-defined]

Also, the result of the LoRA isn't very good, so I'm not sure if its because of this warning or the training itself.

**Comment by robertvoy** [comment]
I was informed: its torch related to the code used, its only a warning and everyone get it

**Comment by lkwfive** [comment]
I'm having the same problem, need a torch downgrade?
