### ISSUE TITLE
Alpha is ignored

### ISSUE THREAD

**Issue by Deathawaits4** [ostris/ai-toolkit#157]
## This is for bugs only

Did you already ask [in the discord](https://discord.gg/VXmU2f5WEU)? 

Yes
You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

## Describe the bug

When setting linear alpha it still builds a 128 dim and 128 alpha network which is either a bug in the log or it ignores alpha value which would be a major bug. 

"type": "sd_trainer",
    "training_folder": "output",
    "device": "cuda:0",
    "network": {
        "type": "lora",
        "linear": 128,
        "linear_alpha": 1,
        "network_kwargs": {
            "only_if_contains": [
                "transformer.single_transformer_blocks.2.proj_out",
                "transformer.single_transformer_blocks.20.proj_out",
                "transformer.single_transformer_blocks.7.proj_out"
                
                
create LoRA network. base dim (rank): 128, alpha: 128

**Comment by NBSTpeterhill** [comment]
Same question happened to me.

**Comment by surebert** [comment]
As a temporary work around, you can set it on lines 24,25 of assistant_lora.py  it then takes those values and ignores the config file

**Comment by jaretburkett** [comment]
For flux, alpha is currently ignored as it is saved in diffusers format which does not have an alpha.
