### ISSUE TITLE
Can't train slider on NAI

### ISSUE THREAD

**Issue by Poiuytrezay1** [ostris/ai-toolkit#17]
I have tried running the slider script on NAI models, but I get an error every time. The example worked just fine.

On the fp16 safetensors version, I get the error: _AttributeError: 'CLIPTextModel' object has no attribute 'embeddings'_
On the original ckpt version, I get the error: _KeyError: 'time_embed.0.weight'_

I've tried changing the dtype, but to no avail. Any chance to fix this?

**Comment by jaretburkett** [comment]
It is an issue with those models. They use a non standard format or something is corrupted. I am not 100% sure. I load models through diffusers, so their library doesn't support it. I think there are some fixed versions of the models out there that are compatible with diffuser, but not sure where to get them.
