### ISSUE TITLE
Flux Lora producing blurry images

### ISSUE THREAD

**Issue by zhini-web** [ostris/ai-toolkit#171]
I trained a Lora for a dress on flux and it gives me blurry results. I am using it at weights 1 and 1.3, but training other dresses does not produce this effect. Why is this?
![ComfyUI_01460_](https://github.com/user-attachments/assets/df815d83-a582-43e9-86e5-3b374c7d59f6)

**Comment by nitinh12** [comment]
What network dim and alpha are you using? It happened with me as well turns out flux learns even the bad quality from the images if you are using 128 network dim and alpha reduce it ti 64. It worked for me
