### ISSUE TITLE
Issue: Symmetric Outputs Despite Asymmetric Training Data in Flux Dev LoRA

### ISSUE THREAD

**Issue by shockman100** [ostris/ai-toolkit#174]
I'm using aI-toolkit with Flux Dev for LoRA training. I'm working with images that feature an asymmetric face, but the model consistently produces symmetric results during training.

I've verified that mirroring is disabled in both the job configuration and in config_modules.py, yet the output still appears to be mirrored.

Is there a known reason for this behavior or something I might be overlooking? Any advice on how to resolve this would be greatly appreciated.

**Comment by jaretburkett** [comment]
overcoming flux's composition and symmetry will be difficult. It is a big model. Some things seem almost impossible to train into it.
