### ISSUE TITLE
TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by protector131090** [ostris/ai-toolkit#207]
========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "S:\ai-toolkit\run.py", line 90, in <module>
    main()
  File "S:\ai-toolkit\run.py", line 86, in main
    raise e
  File "S:\ai-toolkit\run.py", line 78, in main
    job.run()
  File "S:\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "S:\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1741, in run
    loss_dict = self.hook_train_loop(batch_list)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\extensions_built_in\sd_trainer\SDTrainer.py", line 1635, in hook_train_loop
    self.scaler.step(self.optimizer)
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\amp\grad_scaler.py", line 457, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\amp\grad_scaler.py", line 352, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\optim\lr_scheduler.py", line 137, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\optim\optimizer.py", line 487, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\bitsandbytes\optim\optimizer.py", line 291, in step
    self.update_step(group, p, gindex, pindex)
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\bitsandbytes\optim\optimizer.py", line 569, in update_step
    F.optimizer_update_8bit_blockwise(
  File "S:\ai-toolkit\venv3\Lib\site-packages\bitsandbytes\functional.py", line 1843, in optimizer_update_8bit_blockwise    ct.c_float(alpha),
    ^^^^^^^^^^^^^^^^^
TypeError: must be real number, not NoneType
Clover_R32_ohwx:  31%|█████████████████████▌                                               | 2500/8000 [00:05<?, ?it/s]

REM Pause to see any output or errors

Microsoft Windows [Version 10.0.19045.5011]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\user>@echo off
REM Navigate to the virtual environment directory
cd /d S:\ai-toolkit\venv3\Scripts

REM Activate the virtual environment
call activate

REM Navigate to the project directory
cd /d S:\ai-toolkit

REM Run the Python script
python run.py P:\DREAMBOOTH\FLUX\Clover\config.yaml
Running 1 job
S:\ai-toolkit\venv3\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
S:\ai-toolkit\venv3\Lib\site-packages\controlnet_aux\mediapipe_face\mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
S:\ai-toolkit\venv3\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
S:\ai-toolkit\venv3\Lib\site-packages\timm\models\registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
S:\ai-toolkit\venv3\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
S:\ai-toolkit\venv3\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
S:\ai-toolkit\venv3\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
S:\ai-toolkit\venv3\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
S:\ai-toolkit\venv3\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
{
    "type": "sd_trainer",
    "training_folder": "P:\\DREAMBOOTH\\FLUX\\Clover\\model",
    "device": "cuda:0",
    "network": {
        "type": "lora",
        "linear": 32,
        "linear_alpha": 32
    },
    "save": {
        "dtype": "float16",
        "save_every": 250,
        "max_step_saves_to_keep": 40,
        "push_to_hub": false
    },
    "datasets": [
        {
            "folder_path": "P:\\DREAMBOOTH\\FLUX\\Clover\\img",
            "caption_ext": "txt",
            "caption_dropout_rate": 0.05,
            "shuffle_tokens": false,
            "cache_latents_to_disk": true,
            "resolution": [
                1024
            ]
        }
    ],
    "train": {
        "batch_size": 1,
        "steps": 8000,
        "gradient_accumulation_steps": 1,
        "train_unet": true,
        "train_text_encoder": false,
        "gradient_checkpointing": true,
        "noise_scheduler": "flowmatch",
        "optimizer": "adamw8bit",
        "lr": 4e-05,
        "ema_config": {
            "use_ema": true,
            "ema_decay": 0.99
        },
        "dtype": "bf16"
    },
    "model": {
        "name_or_path": "S:\\ai-toolkit\\black-forest-labs\\FLUX.1-dev",
        "is_flux": true,
        "quantize": true
    },
    "sample": {
        "sampler": "flowmatch",
        "sample_every": 500,
        "width": 1024,
        "height": 1024,
        "prompts": [
            "photo of a woman p3r5on, medium shot, holding a coffe cup with text: Clover , and city in the background"
        ],
        "neg": "",
        "seed": 42,
        "walk_seed": true,
        "guidance_scale": 3,
        "sample_steps": 20
    }
}
Using EMA
S:\ai-toolkit\extensions_built_in\sd_trainer\SDTrainer.py:61: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler()

#############################################
# Running job: Clover_R32_ohwx
#############################################

Running  1 process
Loading Flux model
Loading transformer
Quantizing transformer
Loading vae
Loading t5
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  6.56it/s]
Quantizing T5
Loading clip
making pipe
preparing
create LoRA network. base dim (rank): 32, alpha: 32
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder: 0 modules.
create LoRA for U-Net: 494 modules.
enable LoRA for U-Net
#### IMPORTANT RESUMING FROM P:\DREAMBOOTH\FLUX\Clover\model\Clover_R32_ohwx\Clover_R32_ohwx_000002500.safetensors ####
Loading from P:\DREAMBOOTH\FLUX\Clover\model\Clover_R32_ohwx\Clover_R32_ohwx_000002500.safetensors
Missing keys: []
Found step 2500 in metadata, starting from there
Loading optimizer state from P:\DREAMBOOTH\FLUX\Clover\model\Clover_R32_ohwx\optimizer.pt
Updating optimizer LR from params
Dataset: P:\DREAMBOOTH\FLUX\Clover\img
  -  Preprocessing image dimensions
100%|██████████████████████████████████████████████████████████████████████████████████████████| 34/34 [00:00<?, ?it/s]
  -  Found 34 images
Bucket sizes for P:\DREAMBOOTH\FLUX\Clover\img:
832x1216: 23 files
1024x960: 1 files
960x1024: 2 files
1024x1024: 1 files
1216x832: 1 files
960x832: 1 files
1088x960: 1 files
1152x896: 1 files
960x896: 1 files
896x896: 1 files
896x960: 1 files
11 buckets made
Caching latents for P:\DREAMBOOTH\FLUX\Clover\img
 - Saving latents to disk
Caching latents to disk: 100%|██████████████████████████████████████████████████████| 34/34 [00:00<00:00, 11230.61it/s]
Clover_R32_ohwx:  31%|█████████████████████▌                                               | 2500/8000 [00:00<?, ?it/s]Error running job: must be real number, not NoneType

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "S:\ai-toolkit\run.py", line 90, in <module>
    main()
  File "S:\ai-toolkit\run.py", line 86, in main
    raise e
  File "S:\ai-toolkit\run.py", line 78, in main
    job.run()
  File "S:\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "S:\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1741, in run
    loss_dict = self.hook_train_loop(batch_list)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\extensions_built_in\sd_trainer\SDTrainer.py", line 1635, in hook_train_loop
    self.scaler.step(self.optimizer)
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\amp\grad_scaler.py", line 457, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\amp\grad_scaler.py", line 352, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\optim\lr_scheduler.py", line 137, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\optim\optimizer.py", line 487, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\bitsandbytes\optim\optimizer.py", line 291, in step
    self.update_step(group, p, gindex, pindex)
  File "S:\ai-toolkit\venv3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "S:\ai-toolkit\venv3\Lib\site-packages\bitsandbytes\optim\optimizer.py", line 569, in update_step
    F.optimizer_update_8bit_blockwise(
  File "S:\ai-toolkit\venv3\Lib\site-packages\bitsandbytes\functional.py", line 1843, in optimizer_update_8bit_blockwise    ct.c_float(alpha),
    ^^^^^^^^^^^^^^^^^
TypeError: must be real number, not NoneType
Clover_R32_ohwx:  31%|█████████████████████▌                                               | 2500/8000 [00:05<?, ?it/s]

REM Pause to see any output or errors

**Comment by johnyjharris** [comment]
I had this issue when trying to continue a flux training session after updating to the latest repo version. In the end I did a clean install and restarted the training from scratch and it worked. Don't really know why though, not sure even sure you need to do the clean install, but just maybe restart your training from scratch.

**Comment by protector131090** [comment]
> I had this issue when trying to continue a flux training session after updating to the latest repo version. In the end I did a clean install and restarted the training from scratch and it worked. Don't really know why though, not sure even sure you need to do the clean install, but just maybe restart your training from scratch.

yes. that did help. thanks.
