### ISSUE TITLE
Colab - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu

### ISSUE THREAD

**Issue by justcoding88** [ostris/ai-toolkit#212]
## This is for bugs only

Did you already ask [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

## Describe the bug

Using the notebook from here: /notebooks/FLUX_1_dev_LoRA_Training.ipynb 

This was working a few weeks ago. Now, on this step - **run_job(job_to_run)**

RuntimeError                              Traceback (most recent call last)

```
[<ipython-input-11-8519949f2c4c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 run_job(job_to_run)

9 frames

[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/flux/pipeline_flux.py](https://localhost:8080/#) in _prepare_latent_image_ids(batch_size, height, width, device, dtype)
    429     def _prepare_latent_image_ids(batch_size, height, width, device, dtype):
    430         latent_image_ids = torch.zeros(height, width, 3, device=device, dtype=dtype)
--> 431         latent_image_ids[..., 1] = latent_image_ids[..., 1] + torch.arange(height)[:, None]
    432         latent_image_ids[..., 2] = latent_image_ids[..., 2] + torch.arange(width)[None, :]
    433 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

No changes have been made to the notebook, the exact same thing was working a few weeks ago on the same device (Colab, A100).

Please, how do we resolve this?

**Comment by justcoding88** [comment]
...closing this issue. Issue appears to be with **diffusers** . Resolution was to revert to an older version by modifying requirements.txt and using this version:

`git+https://github.com/huggingface/diffusers.git@v0.30.1`

**Comment by BenDes21** [comment]
> git+https://github.com/huggingface/diffusers.git@v0.30.1

fixed, thanks a lot
