### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by BenDes21** [ostris/ai-toolkit#214]
Hi there ! Getting this error today with a new runpod instance ( same template as usual ) and same config file as usual also... anyone know where its can come from ? Thanks a lot 

[
<img width="1035" alt="Untitled" src="https://github.com/user-attachments/assets/772429c2-517a-40ae-b8f6-9cfb16a46555">
](url)

**Comment by lhovav** [comment]
same for me

**Comment by lhovav** [comment]
hi @BenDes21 , check this out, it solved my issue:
https://github.com/ostris/ai-toolkit/issues/212

**Comment by BenDes21** [comment]
> hi @BenDes21 , check this out, it solved my issue: #212

fixed, thanks a lot
