### ISSUE TITLE
A matching Triton is not available, some optimizations will not be enabled

### ISSUE THREAD

**Issue by sbuldan** [ostris/ai-toolkit#26]
I am on windows 10 with a rtx 3090
Installed triton manualy but not sure installed it in the right folder or correct version. I need some help here.

Running 1 job
Z:\SDZ\ai-toolkit\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Z:\SDZ\ai-toolkit\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "Z:\SDZ\ai-toolkit\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "Z:\SDZ\ai-toolkit\venv\lib\site-packages\xformers\triton\softmax.py", line 14, in <module>
    from xformers.triton.k_softmax import _softmax, _softmax_backward
  File "Z:\SDZ\ai-toolkit\venv\lib\site-packages\xformers\triton\k_softmax.py", line 8, in <module>
    import triton.language as tl
ModuleNotFoundError: No module named 'triton.language'
Z:\SDZ\ai-toolkit\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Z:\SDZ\ai-toolkit\venv\lib\site-packages\diffusers\models\unet_2d_condition.py:20: FutureWarning: `UNet2DConditionOutput` is deprecated and will be removed in version 0.29. Importing `UNet2DConditionOutput` from `diffusers.models.unet_2d_condition` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_condition import UNet2DConditionOutput`, instead.
  deprecate("UNet2DConditionOutput", "0.29", deprecation_message)
Z:\SDZ\ai-toolkit\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Z:\SDZ\ai-toolkit\venv\lib\site-packages\diffusers\models\unet_2d_condition.py:25: FutureWarning: `UNet2DConditionModel` is deprecated and will be removed in version 0.29. Importing `UNet2DConditionModel` from `diffusers.models.unet_2d_condition` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_condition import UNet2DConditionModel`, instead.
  deprecate("UNet2DConditionModel", "0.29", deprecation_message)
{
    "type": "slider",
    "network": {
        "type": "lierla",
        "linear": 8,
        "linear_alpha": 4
    },
    "train": {
        "noise_scheduler": "ddpm",
        "steps": 500,
        "lr": 0.0002,
        "gradient_checkpointing": true,
        "train_unet": true,
        "train_text_encoder": false,
        "min_snr_gamma": 5.0,
        "optimizer": "adamw",
        "lr_scheduler": "constant",
        "max_denoising_steps": 40,
        "batch_size": 1,
        "dtype": "bf16",
        "noise_offset": 0.0357
    },
    "model": {
        "name_or_path": "./albedobaseXL_v21.safetensors",
        "is_v2": false,
        "is_v_pred": false,
        "is_xl": false
    },
    "save": {
        "dtype": "float16",
        "save_every": 50,
        "max_step_saves_to_keep": 2
    },
    "sample": {
        "sampler": "ddpm",
        "sample_every": 20,
        "width": 512,
        "height": 512,
        "prompts": [
            "a woman in a coffee shop, black hat, blonde hair, blue jacket --m -5",
            "a woman in a coffee shop, black hat, blonde hair, blue jacket --m -3",
            "a woman in a coffee shop, black hat, blonde hair, blue jacket --m 3"
        ],
        "neg": "cartoon, fake, drawing, illustration, cgi, animated, anime, monochrome",
        "seed": 42,
        "walk_seed": false,
        "guidance_scale": 7,
        "sample_steps": 20,
        "network_multiplier": 1.0
    },
    "logging": {
        "log_every": 10,
        "use_wandb": false,
        "verbose": false
    },
    "slider": {
        "resolutions": [
            [
                1024,
                1024
            ]
        ],
        "batch_full_slide": true,
        "targets": [
            {
                "target_class": "",
                "positive": "high detail, 8k, intricate, detailed, high resolution, high res, high quality",
                "negative": "blurry, boring, fuzzy, low detail, low resolution, low res, low quality",
                "weight": 1.0,
                "shuffle": true
            }
        ]
    }
}
Building slider targets
Built 8 slider targets (with permutations)

#############################################
# Running job: detail_slider_v1
#############################################

Running  1 process
Error running job: StableDiffusionPipeline.__init__() got an unexpected keyword argument 'tokenizer_2'

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "Z:\SDZ\ai-toolkit\run.py", line 89, in <module>
    main()
  File "Z:\SDZ\ai-toolkit\run.py", line 85, in main
    raise e
  File "Z:\SDZ\ai-toolkit\run.py", line 77, in main
    job.run()
  File "Z:\SDZ\ai-toolkit\jobs\TrainJob.py", line 49, in run
    process.run()
  File "Z:\SDZ\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1075, in run
    self.sd.load_model()
  File "Z:\SDZ\ai-toolkit\toolkit\stable_diffusion_model.py", line 283, in load_model
    pipe = pipln.from_single_file(
  File "Z:\SDZ\ai-toolkit\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "Z:\SDZ\ai-toolkit\venv\lib\site-packages\diffusers\loaders\single_file.py", line 274, in from_single_file
    pipe = pipeline_class(**init_kwargs)
TypeError: StableDiffusionPipeline.__init__() got an unexpected keyword argument 'tokenizer_2'

**Comment by ItsAuver** [comment]
At the time of this comment, Triton has been compiled/ported to Windows to the best of my knowledge. See https://github.com/openai/triton/issues/1640

**Comment by DarkAlchy** [comment]
It never will be the devs said last year.  The best we have  is just a wrapper around 500mb for 2.1 cuda.
