### ISSUE TITLE
Sorry, I'm not even sure how to use it!

### ISSUE THREAD

**Issue by tsjslgy** [ostris/ai-toolkit#30]
I've used tools like Leco and Forge before because they have .bat or .ps executable files, but I've searched through all the directories and haven't found any for this. Sorry, I'm not a programmer, so I'm not very familiar with this. I've found a .py script, but I can't run it or see the training process. I've searched on YouTube, but there aren't any tutorials. Can anyone help me figure out what to do?

**Comment by user83922** [comment]
Did you install and configure everything?

Then it's just activating the venv and running "run.py" pointing towards the configured *.yaml file.

https://github.com/ostris/ai-toolkit?tab=readme-ov-file#installation

Example in an activated venv: $ python run.py config\foo.yaml
