### ISSUE TITLE
FLUX example config

### ISSUE THREAD

**Issue by OliviaOliveiira** [ostris/ai-toolkit#32]
Hey! 
I saw you and your ai-toolkit here https://github.com/black-forest-labs/flux/issues/9 and was wondering if you could share the config file and a bit of instructions to get it going since it'll be benefitial for both sides, us as users, and you as dev. 
Thanks in advance!

**Comment by martintomov** [comment]
@OliviaOliveiira 

Hi! 
Did you try to train with the new instructions and configs provided?

**Comment by OliviaOliveiira** [comment]
> @OliviaOliveiira
> 
> Hi! Did you try to train with the new instructions and configs provided?

Hey! I did not, I’ve returned to SimpeTuner and stay there till now, will probably try it during the following days

**Comment by martintomov** [comment]
Check this out: https://github.com/ostris/ai-toolkit/blob/main/notebooks/FLUX_1_dev_LoRA_Training.ipynb

**Comment by martintomov** [comment]
By the way, are your LoRAs turning out to be good with SimpleTuner?

**Comment by OliviaOliveiira** [comment]
> By the way, are your LoRAs turning out to be good with SimpleTuner?

So far quite good, although, the styles the model is quite unfamiliar (anime-ish) are quite difficult to train, still wondering a proper and optimal way to solve this. No questions to SimpleTuner, check it out yourself)
