### ISSUE TITLE
Error training Schnell

### ISSUE THREAD

**Issue by davizca** [ostris/ai-toolkit#38]
Successfully trained on Dev but on Schnell something weird happens:

"RuntimeError: CUDA error: unknown error CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1"

Readed that I need to add: --disable-cuda-malloc ?? or something like that, maybe?

**Comment by martintomov** [comment]
Flux Schnell cannot be trained (for now) since it's a distilled model, the training dynamics are different from flux-dev.

You can check this out:
https://huggingface.co/ostris/OpenFLUX.1

**Comment by davizca** [comment]
Totally. You are right. I will try simpletuner too but maybe same fate. Thanks for the answer!

**Comment by jaretburkett** [comment]
Training on schnell is now supported
