### ISSUE TITLE
i can´t create a .env file in the runpod console!

### ISSUE THREAD

**Issue by merecesarchviz** [ostris/ai-toolkit#39]
hi,

I set all in the runpod but then in this last step to create a file .env to add the token the jypyter don't let create this kind of files!! exist a workaround for this?

**Comment by longding717** [comment]
Try saving the txt file as, selecting all files, and then manually typing .env
![6CE6596F70729BEB6FB1D1576B3B6F79](https://github.com/user-attachments/assets/694207d4-28a2-4e04-95c8-99b92c4e06e3)

**Comment by merecesarchviz** [comment]
> Try saving the txt file as, selecting all files, and then manually typing .env ![6CE6596F70729BEB6FB1D1576B3B6F79](https://private-user-images.githubusercontent.com/114659494/357305810-694207d4-28a2-4e04-95c8-99b92c4e06e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDEzMzMsIm5iZiI6MTcyMzU0MTAzMywicGF0aCI6Ii8xMTQ2NTk0OTQvMzU3MzA1ODEwLTY5NDIwN2Q0LTI4YTItNGUwNC05NWM4LTk5YjkyYzRlMDZlMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwOTIzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDAyNTdjZmE4YzA0MjBiMWQyYzIyMWIyMTM2ZjZiYmZiYWE2YzBiNDY5YzM1ZjFjYjE2YzJlMjMwYmFhZDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.um3B2-wd1FzPUqfcrO4AxeBx-vOBuP651YJ1ycwTijE)

i know how to create the .env file locally in my computer the problem is that runpod in jupyther when i try to unpload it or create the file there dont allow it the both ways! it seems is not accepted that kind files in runpod!

**Comment by merecesarchviz** [comment]
I find a solution, i deploy in runpod the Kohya_ss GUI template and i install all there without issues! running perfectly
