### ISSUE TITLE
ImportError: cannot import name 'packaging' from 'pkg_resources'

### ISSUE THREAD

**Issue by Anibaaal** [ostris/ai-toolkit#40]
I set up everything according to the Readme and this guide video https://www.youtube.com/watch?v=HzGW_Kyermg, but I'm getting this error after a reinstall because dotenv failed to install the first time:

Running 1 job
Error running job: cannot import name 'packaging' from 'pkg_resources' (C:\StableDiffusion\Training\ai-toolkit\venv\Lib\site-packages\pkg_resources\__init__.py)

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "C:\StableDiffusion\Training\ai-toolkit\run.py", line 90, in <module>
    main()
  File "C:\StableDiffusion\Training\ai-toolkit\run.py", line 86, in main
    raise e
  File "C:\StableDiffusion\Training\ai-toolkit\run.py", line 77, in main
    job = get_job(config_file, args.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\StableDiffusion\Training\ai-toolkit\toolkit\job.py", line 28, in get_job
    from jobs import ExtensionJob
  File "C:\StableDiffusion\Training\ai-toolkit\jobs\__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "C:\StableDiffusion\Training\ai-toolkit\jobs\BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "C:\StableDiffusion\Training\ai-toolkit\jobs\process\__init__.py", line 8, in <module>
    from .TrainSliderProcess import TrainSliderProcess
  File "C:\StableDiffusion\Training\ai-toolkit\jobs\process\TrainSliderProcess.py", line 26, in <module>
    from .BaseSDTrainProcess import BaseSDTrainProcess
  File "C:\StableDiffusion\Training\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 39, in <module>
    from toolkit.sampler import get_sampler
  File "C:\StableDiffusion\Training\ai-toolkit\toolkit\sampler.py", line 22, in <module>
    from k_diffusion.external import CompVisDenoiser
  File "C:\StableDiffusion\Training\ai-toolkit\venv\Lib\site-packages\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "C:\StableDiffusion\Training\ai-toolkit\venv\Lib\site-packages\k_diffusion\evaluation.py", line 6, in <module>
    import clip
  File "C:\StableDiffusion\Training\ai-toolkit\venv\Lib\site-packages\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "C:\StableDiffusion\Training\ai-toolkit\venv\Lib\site-packages\clip\clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\StableDiffusion\Training\ai-toolkit\venv\Lib\site-packages\pkg_resources\__init__.py)

**Comment by Anibaaal** [comment]
Ohh, I completely forgot about this error when updating git submodules, might be related to the error above? :

Cloning into 'C:/StableDiffusion/Training/ai-toolkit/repositories/batch_annotator/repositories/controlnet'...
error: unable to create file annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierFloatEfficientNet.java: Filename too long
error: unable to create file annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierFloatMobileNet.java: Filename too long
error: unable to create file annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierQuantizedEfficientNet.java: Filename too long
error: unable to create file annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierQuantizedMobileNet.java: Filename too long
error: unable to create file annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_task_api/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierFloatEfficientNet.java: Filename too long
error: unable to create file annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_task_api/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierFloatMobileNet.java: Filename too long
error: unable to create file annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_task_api/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierQuantizedEfficientNet.java: Filename too long
error: unable to create file annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_task_api/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierQuantizedMobileNet.java: Filename too long
fatal: Unable to checkout 'e2b44154b72965c5e11b1ccee941d550682e4701' in submodule path 'repositories/batch_annotator/repositories/controlnet'
fatal: Failed to recurse into submodule path 'repositories/batch_annotator'

**Comment by Anibaaal** [comment]
Solved by replacing line 6 in ai-toolkit\venv\Lib\site-packages\clip\clip.py
from from 'pkg_resources import packaging' to 'import packaging'
as suggested here https://github.com/pytorch/serve/issues/3176

**Comment by etha302** [comment]
> Solved by replacing line 6 in ai-toolkit\venv\Lib\site-packages\clip\clip.py from from 'pkg_resources import packaging' to 'import packaging' as suggested here [pytorch/serve#3176](https://github.com/pytorch/serve/issues/3176)

thanks you saved me hours of work!

**Comment by diodiogod** [comment]
I solved this with gpt help by doing 
pip install --upgrade setuptools
and then 
py -m pip install --upgrade pip setuptools wheel

**Comment by HydraBucket** [comment]
Thank you random @diodiogod , I love random Githubbers and redditors for a random tech issue. Lora is training because of you and some guy in youtube comments!

**Comment by TalhaKarakoyunlu** [comment]
thanks, fixed the issue
