### ISSUE TITLE
Error running job: black-forest-labs/FLUX.1-dev does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by z3300200** [ostris/ai-toolkit#47]
![微信截图_20240813172518](https://github.com/user-attachments/assets/e898ba58-0101-4fc5-a27c-df845fcfd06a)

**Comment by maxenko** [comment]
Same issue.

**Comment by Aderek514** [comment]
Same issue...

**Comment by abozahran** [comment]
I grapped all files saved in .cash in my user profile on windows and made same folders as in this link https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main
then copied tha path to config file as model source path

**Comment by Aderek514** [comment]
I will try this tip with cache.. i always download all folders from huggie
because i use onetrainer and it cant read sd3 fto huggie

sob., 17 sie 2024, 13:55 użytkownik abozahran ***@***.***>
napisał:

**Comment by jaretburkett** [comment]
Closing for now. Let me know if not resolved.

**Comment by MatthijsOord** [comment]
> Same issue... but after download files from huge this error disapear: https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main/transformer

To what specific folder did you place the downloaded files?

**Comment by leo-hong6** [comment]
I successfully solved this problem. Solution: Re-enter the token from Hugging Face. Remember to use the token with the read function.

**Comment by leo-hong6** [comment]
我成功解决了这问题。解决方案：重新输入huggingface的tooken，注意一定要read功能的tooken
