### ISSUE TITLE
not a bug:feature continue training

### ISSUE THREAD

**Issue by kigy1** [ostris/ai-toolkit#48]
i wish if can I stop training and continue training again with different settings and a different dataset?

I know, some people may wonder why. After training, it may appear that some of the images are not essential, or we have had enough of them in training and want to remove them in the middle of training. Also, the model may forget a certain concept, and I wish I could stop the training and provide him with pictures only of the concept with a few steps, then continue the basic training

It may help us a lot when training the large model.
or at a certain point, we add images, focus on them, then remove them, and continue training

that give us Flexible traning.

**Comment by Desm0nt** [comment]
You can continue you training. Just run again with the same config and it will start from last checkpoint. You even can change config or images, just don't change lora rank and alpha and don't remove anything from lora output folder.

**Comment by skein12** [comment]
yeah just leave everything in output you'll get this message when the training is loading

#### IMPORTANT RESUMING FROM /home/torch/AI/Training/Model/my_first_flux_lora_v1/my_first_flux_lora_v1.safetensors ####

**Comment by kigy1** [comment]
> You can continue you training. Just run again with the same config and it will start from last checkpoint. You even can change config or images, just don't change lora rank and alpha and don't remove anything from lora output folder.

Thanks, I think this will work

**Comment by kigy1** [comment]
> yeah just leave everything in output you'll get this message when the training is loading
> 
> #### IMPORTANT RESUMING FROM /home/torch/AI/Training/Model/my_first_flux_lora_v1/my_first_flux_lora_v1.safetensors

Thanks, I think this will work

**Comment by astridmentzer** [comment]
hmm. When I try this it starts from scratch everytime.
