### ISSUE TITLE
please help! Where to put black-forest-labs/FLUX.1-dev if i already downloaded it? 

### ISSUE THREAD

**Issue by protector131090** [ostris/ai-toolkit#49]
please help! Where to put black-forest-labs/FLUX.1-dev if i already downloaded it?   git cloning speed is 100kb/s it will take weeks. Where do i put already downloaded folder from [black-forest-labs/FLUX.1-dev](https://huggingface.co/black-forest-labs/FLUX.1-dev) to use it without downloading from HF ?? thanks!

**Comment by protector131090** [comment]
solved with this https://github.com/ostris/ai-toolkit/issues/46

**Comment by maxenko** [comment]
Not working with fix proposed in #46 for me.

**Comment by protector131090** [comment]
> Not working with fix proposed in #46 for me.

did you put the whole folder? its 107 gb.

**Comment by jaretburkett** [comment]
The contents of the entire folder are required in the folder. Then pointing to a local path should work. Let me know if this doesn't work.

**Comment by hotdogarea** [comment]
> The contents of the entire folder are required in the folder. Then pointing to a local path should work. Let me know if this doesn't work.

        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "/root/ComfyUI/models/unet/flux_dev.safetensors"  

it does'nt work for linux!  this is absolute file path

**Comment by hotdogarea** [comment]
> Not working with fix proposed in #46 for me.不适用于中建议的修复 #46 为我。

for linux ,have u solved this problem?

**Comment by 1247862674** [comment]
How to configure it under Linux, I have to download the model in /data/app/models/FLUX.1-dev

**Comment by 1247862674** [comment]
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /data/app/models/black-forest-labs/FLUX.1-dev is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
