### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found. Error loading "D:\ai-toolkit\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by protector131090** [ostris/ai-toolkit#50]
I reinstalled 4 times. Does not help. What can be the reson? 

**(venv) D:\ai-toolkit>pip show torch
Name: torch
Version: 2.4.0+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: d:\ai-toolkit\venv\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, bitsandbytes, clean-fid, clip-anytorch, controlnet-aux, dctorch, invisible-watermark, k-diffusion, kornia, lpips, lycoris-lora, open_clip_torch, optimum-quanto, pytorch-fid, timm, torchdiffeq, torchsde, torchvision**

(venv) D:\ai-toolkit>

(venv) D:\ai-toolkit>python run.py config/FLUX_MINE.yaml
Running 1 job
Error running job: [WinError 126] The specified module could not be found. Error loading "D:\ai-toolkit\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "D:\ai-toolkit\run.py", line 90, in <module>
    main()
  File "D:\ai-toolkit\run.py", line 86, in main
    raise e
  File "D:\ai-toolkit\run.py", line 77, in main
    job = get_job(config_file, args.name)
  File "D:\ai-toolkit\toolkit\job.py", line 28, in get_job
    from jobs import ExtensionJob
  File "D:\ai-toolkit\jobs\__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "D:\ai-toolkit\jobs\BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "D:\ai-toolkit\jobs\process\__init__.py", line 1, in <module>
    from .BaseExtractProcess import BaseExtractProcess
  File "D:\ai-toolkit\jobs\process\BaseExtractProcess.py", line 4, in <module>
    from safetensors.torch import save_file
  File "D:\ai-toolkit\venv\lib\site-packages\safetensors\torch.py", line 6, in <module>
    import torch
  File "D:\ai-toolkit\venv\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "D:\ai-toolkit\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

(venv) D:\ai-toolkit>

**Comment by protector131090** [comment]
solved by copying https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download to windows/system 32

**Comment by ooyey** [comment]
Another option is use conda:
Create env
```
conda create -n FluxTrain python=3.10 -y
```

Activate env and install requirements
torch and torchvision may be excluded from requirements.txt or removed later
```
conda activate FluxTrain
pip install -r requirements.txt
```

Remove torch and torchvision, if already installed
```
pip uninstall torch torchvision
```

Install torch with conda
https://pytorch.org/
```
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
```

Run training
```
conda activate FluxTrain
python run.py config/your_config_file.yml
```

**Comment by Mounish2023** [comment]
> solved by copying https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download to windows/system 32

I am also facing this error. what do you mean by this. I am new to this. Can you explain some more on this? Thanks in advance.

**Comment by Mounish2023** [comment]
I figured it out in a youtube link. Thanks. https://www.youtube.com/watch?v=8RwsfTu_nqM

**Comment by ambrosektal** [comment]
> solved by copying https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download to windows/system 32

THANK YOU!

**Comment by jiyadkamal** [comment]
Thanks dude, great help
