### ISSUE TITLE
I have a few quick questions for the family

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [ostris/ai-toolkit#53]
Hello thank you for this tool and amazing scripts

I am blessed doing some Lora training for flux models but wanted to see if there is a few things I can improve on workflow

so first off is there a way to use wandb in the config to repot and keep track of stuff in real time.

Then is there a way to possible modify the script or add something to play super loud noise soundclip this way I can wake my ass up to turn off my run pod and not waste credits

Also possible update with async my models and repos to my hugging face to ensure I do not loose anything

Know its a lot but figured could be useful others you know.

Blessed for this and future of AI and tech

**Comment by jaretburkett** [comment]
Most of these things are planned/in PR/ in the works. The churp thing may not happen. However, it is east to build custom plugins to do things like that. I will try to document this further in the near future.
