### ISSUE TITLE
Bug on the [TRIGGER] Implementation of the sample .yaml

### ISSUE THREAD

**Issue by Dawgmastah** [ostris/ai-toolkit#54]
When seeing the samples on my lora training, I noticed a person on one of the images had [TRIGGER] with letters written on their shirt.
This means that the trigger is not being properly replaced by the trigger worked and rpomped for sample as is.

**Comment by WarAnakin** [comment]
you need to enable and define the trigger word in order for this to work properly.
Uncomment that setting like in my example
![image](https://github.com/user-attachments/assets/29ac8459-b28f-4c3f-81d3-0279938a94fd)

**Comment by xdfin99** [comment]
so if the trigger word is not commented out (enabled in the script), is it simply not needed when using that Lora in comfyui?

**Comment by jaretburkett** [comment]
Yes, it will only replace [trigger] if there is a `trigger_word` defined, otherwise it is processed as the plain text `[trigger]`

**Comment by ignacio-amaya-rovio** [comment]
I did face this issue today in some images and I had `trigger_word` not commented out. Only happened twice, so I wonder if there is a bug in some cases 🤔

**Comment by electricazimuth** [comment]
I'm also seeing this, I think it's down to the `cache_sample_prompts` not doing the string replacement before caching the prompts.
