### ISSUE TITLE
ModuleNotFoundError: No module named 'oyaml'

### ISSUE THREAD

**Issue by oliverban** [ostris/ai-toolkit#56]
I've successfully trained 5 loras but now I am getting this when trying to run a job, any ideas?

```
C:\Users\Oliver\Documents\Github\ai-toolkit>python run.py config/trainFlux.yml
Traceback (most recent call last):
  File "C:\Users\Oliver\Documents\Github\ai-toolkit\run.py", line 22, in <module>
    from toolkit.job import get_job
  File "C:\Users\Oliver\Documents\Github\ai-toolkit\toolkit\job.py", line 3, in <module>
    from toolkit.config import get_config
  File "C:\Users\Oliver\Documents\Github\ai-toolkit\toolkit\config.py", line 5, in <module>
    import oyaml as yaml
ModuleNotFoundError: No module named 'oyaml'
```

I've tried reinstalling requirements and git pull shows already updated.

EDIT:
It seems I can delete the VENV, re-install everything from that point on, run ONE (1) job and then the error comes back if I cancel or finish it and want to start a new one.

**Comment by oliverban** [comment]
bump!

**Comment by sumanthdonapati** [comment]
just do `pip install oyaml`

**Comment by WarAnakin** [comment]
check your file extension

**Comment by oliverban** [comment]
> just do `pip install oyaml`

I already did.

> check your file extension

It is correct.

FIXED IT BY:
uninstall oyaml, **install pandas**, force install and upgrade oyaml again, this worked for me.

**Comment by 487306** [comment]
I had the same problem, did you solve it?

**Comment by 487306** [comment]
Thank you, we've solved this step. But it's not running yet

**Comment by jaretburkett** [comment]
This generally happens when the venv is not activated or the requirements are not installed. Try to run through the install process again and watch for errors and report back if it still doesn't work. 

Midding UMT5EncoderModel module is from transformers needing to be updated to newer version. run `pip install --upgrade -r requirements.txt` inside the venv.
