### ISSUE TITLE
【Question】Will we have ref (dreambooth-like) train in future ? And checkpoint funtune ?

### ISSUE THREAD

**Issue by NBSTpeterhill** [ostris/ai-toolkit#58]
Dear Author:
Can we use ref datasets in the future ?
And checkpoint futunate ?
Thanks

**Comment by protector131090** [comment]
yes

**Comment by WarAnakin** [comment]
ref?

**Comment by jaretburkett** [comment]
All of this is technically possible but I have not tested with the latest changes. It will not work quantized, but should work `bf16`. You will need 80gb of vram. All you need to do is comment out the `network` section and it will do a full finetune. I will make sure this works properly and update the docs in the next few days

**Comment by NBSTpeterhill** [comment]
> All of this is technically possible but I have not tested with the latest changes. It will not work quantized, but should work `bf16`. You will need 80gb of vram. All you need to do is comment out the `network` section and it will do a full finetune. I will make sure this works properly and update the docs in the next few days

Thank you for your reply and neat work on ai-toolkit, happy to wait for the new update.
