### ISSUE TITLE
Help! how do you run an inference with the saved flux lora model?

### ISSUE THREAD

**Issue by kilimchoi** [ostris/ai-toolkit#71]
It seems that something in `GenerateProcess` is handling image generation during training. I was wondering if there are any resources we could take a look to handle image generations with the flux lora model that was just created.

**Comment by martintomov** [comment]
You can upload it as a model to hugging face and use the Inference API, if that works for you

**Comment by AFMSB** [comment]
Is this the only way? i want to make inference on my server, not in the huggingface
