### ISSUE TITLE
The download of pytorch_model-00001-of-00003.safetensors got stuck

### ISSUE THREAD

**Issue by weiwei83** [ostris/ai-toolkit#84]
<img width="938" alt="image" src="https://github.com/user-attachments/assets/17e51163-f4a4-4a38-8a74-5bfec7868322">
The download speed was 50 megabytes per second at the beginning.
As the download approaches completion, the download speed gradually decreases until it drops to several kilobytes. The final result is that I can never complete the download.

**Comment by martintomov** [comment]
Same happened to me, just download the model manually and then use local path as model in config where it reads **name_or_path** :

```
# huggingface model name or path
name_or_path: "f:/5_Training_tools/ai-toolkit/FLUX.1-dev"
```

**Comment by martintomov** [comment]
Same happened to me, just download the model manually and then use local path as model in config where it reads **name_or_path** :

```
# huggingface model name or path
name_or_path: "C:/.../ai-toolkit/FLUX.1-dev"
```

**Comment by Codacodercoda** [comment]
> Same happened to me, just download the model manually and then use local path as model in config where it reads **name_or_path** :
> 
> ```
> # huggingface model name or path
> name_or_path: "C:/.../ai-toolkit/FLUX.1-dev"
> ```
> 
> https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main

That works for the model but then it gets stuck on the text encoder and vae, how do I path them?

edit: gave python.exe write permissions and the downloads started working.

**Comment by Falkonar** [comment]
> > Same happened to me, just download the model manually and then use local path as model in config where it reads **name_or_path** :
> > ```
> > # huggingface model name or path
> > name_or_path: "C:/.../ai-toolkit/FLUX.1-dev"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main
> 
> That works for the model but then it gets stuck on the text encoder and vae, how do I path them?
> 
> edit: gave python.exe write permissions and the downloads started working.

Great solution . But how I can fix it on linux. Same issue
