### ISSUE TITLE
Error running job: 'LoRASpecialNetwork' object has no attribute 'loraplus_unet_lr_ratio'

### ISSUE THREAD

**Issue by seasnakes** [ostris/ai-toolkit#85]
<img width="710" alt="image" src="https://github.com/user-attachments/assets/7f675e72-2888-43f6-8cd1-45ba35bab7d0">

**Comment by jaretburkett** [comment]
Odd, are you passing any kwargs in the network config? Can I see the config?

**Comment by seasnakes** [comment]
fixed .Maybe because I have kohya in my home directory too,so the ai-toolkit tried to call the kohya that I  downloaded long time ago . Anyway,after i  delete the old kohya , it began to work successfully.

**Comment by flankechen** [comment]
@seasnakes you mean ai-toolkit call some other kohyass rather than the local/repositeries ones?
could you check your working kohyass branch? I encounter the same error, but my kohyass is sd3 branch. and flux lora training always work. but some ic-lora error.

**Comment by vvsotnikov** [comment]
I had the same issue after checking out to a specific commit and then checking out to the main branch again. Running `git submodule update --init --recursive` solved the issue.
