### ISSUE TITLE
RunPod cloud config

### ISSUE THREAD

**Issue by martintomov** [ostris/ai-toolkit#90]
_From README:_
> Training in the cloud
Coming very soon. Getting base out then will have a notebook that makes all that work.

# How to train a model in RunPod?
Example RunPod template: **runpod/pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04**
> You need a minimum of 24GB VRAM, pick a GPU by your preference.

#### Example config ($0.5/hr):
- 1x A40 (48 GB VRAM)
- 19 vCPU 100 GB RAM

#### Custom overrides (you need some storage to clone FLUX.1, store datasets, store trained models and samples):
- ~120 GB Disk
- ~120 GB Pod Volume
- Start Jupyter Notebook

### 1. Setup
```
git clone https://github.com/ostris/ai-toolkit.git
cd ai-toolkit
git submodule update --init --recursive
python -m venv venv
source venv/bin/activate
pip install torch
pip install -r requirements.txt
pip install --upgrade accelerate transformers diffusers huggingface_hub  #Optional, run it if you run into issues
```
### 2. Upload your dataset
- Create a new folder in the root, name it `dataset` or whatever you like
- Drag and drop your .jpg and .txt files inside the newly created dataset folder

### 3. Login into Hugging Face with an Access Token
- Get a READ token from [here](https://huggingface.co/settings/tokens)
- Run ```huggingface-cli login``` and paste your token

### 4. Training
- Copy an example config file located at ```config/examples``` to the config folder and rename it to ```whatever_you_want.yml```
- Edit the config following the comments in the file
- Change ```folder_path: "/path/to/images/folder"``` to your dataset path like ```folder_path: "/workspace/ai-toolkit/your-dataset"```
- Run the file: ```python run.py config/whatever_you_want.yml```

### Screenshot from RunPod
<img width="1728" alt="RunPod Training Screenshot" src="https://github.com/user-attachments/assets/53a1b8ef-92fa-4481-81a7-bde45a14a7b5">

**Comment by BenDes21** [comment]
thanks a lot

**Comment by blandpebbles** [comment]
One issue. AI Toolkit does not support Multi GPU so hiring two GPUs is a waste of time. Hire one with 48gb or higher.

**Comment by frailloris** [comment]
Thank you :)

**Comment by BenDes21** [comment]
Hi, I get this error OSError: black-forest-labs/FLUX.1-dev is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models' , I correctly set up the variable HF_TOKEN=my access token

**Comment by martintomov** [comment]
> Hi, I get this error OSError: black-forest-labs/FLUX.1-dev is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models' , I correctly set up the variable HF_TOKEN=my access token

I've updated the guide steps, look at the original post above for the new ```huggingface-cli login``` step.

**Comment by steve84wien** [comment]
Hey, thank you very much for the summary! Is there a LR recommended for a classic photography style LoRA? With SDXL I set it to 1e-05 for model fine tunes and 1e-04 for LoRas.

**Comment by martintomov** [comment]
> Hey, thank you very much for the summary! Is there a LR recommended for a classic photography style LoRA? With SDXL I set it to 1e-05 for model fine tunes and 1e-04 for LoRas.

Experiment with learning rates like 1e-4, 2e-4, 4e-3, ... and others. The key I think, is to find the right balance for your dataset. My current go-to approach is manually captioning the dataset and using a 2e-4 LR for 2000-3000 steps. Alternatively, a 4e-3 LR for around 1000 steps was also highly effective for me. Best tip I can give is to try and find the balance yourself.

### Example, same dataset, 43 images:

#### 2e-4, 2000 steps:
![image](https://github.com/user-attachments/assets/41a3b73f-af44-4c0a-bc0a-f13fa08dd5a5)

#### 4e-3, 1000 steps:
![image](https://github.com/user-attachments/assets/f34a46df-4596-46d5-87b5-b23a53a90651)

**Comment by steve84wien** [comment]
Thank you very much for your recommendations! I will stick to them. I see in your example pictures that you get a plastic looking face which is what I try to avoid so I am not quite sure if that is related to your dataset, the training setting or simply a base model issue that needs to be addressed with bigger fine tunes first.

**Comment by goffy76** [comment]
Hi 

When running the run.py command I get this?

Error running job: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by icebergov** [comment]
hi @goffy76,

1. run
```
cd ai-toolkit
git submodule update --init --recursive
```

2. then try again and install the missing library depending on your operating system:
- For Ubuntu/Debian:
```
sudo apt update
sudo apt install libgl1-mesa-glx
```
- For Arch Linux:
```
sudo pacman -S libglvnd
```

**Comment by goffy76** [comment]
Hi 
I forgot to mention that I run it on Vast.ai (rent a GPU). Does that make a difference??
