### ISSUE TITLE
Subfolders + Saving latents multiple times

### ISSUE THREAD

**Issue by Pirog17000** [ostris/ai-toolkit#93]
I'm using multiple subfolders inside of a main train data folder to sort out files by theme and subject, however, seems like script goes the same amount of times to cache the latents as amount of folders :) It created latents from the first run (at least it looks like it is created), but it does it again and again (and I have like 8 folders).

Might be some sort of unnecessary forloop or something.
![image](https://github.com/user-attachments/assets/c09dc68f-4dcc-4aa4-8633-3c8d94fcb521)

**Comment by Pirog17000** [comment]
erhm... it processed the folders 3 times (less times than amount of folders) and began to train. Not sure why it is separated, but let this ticket be a headsup for the author, this might be done in a single pass possibly or the logic of caching latents could possible do extra runs for no reason

**Comment by Desm0nt** [comment]
> it processed the folders 3 times

It processed separatedly for 3 different resolutions with different batching - 512, 768 and 1024.

**Comment by Pirog17000** [comment]
Got it, thanks.
