### ISSUE TITLE
LoRA runs with errors:ERROR lora diffusion_model.single_blocks.37.linear2.weight Allocation on device

### ISSUE THREAD

**Issue by weiwei83** [ostris/ai-toolkit#96]
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/de893568-dcd3-4c04-8155-8cfcbc9a9daa">
I was training LoRA locally. After running it under ComfyUI, the above error was reported. Has anyone encountered a similar problem? How was it solved?

**Comment by martintomov** [comment]
you should use this script by comfyanonymous to convert the lora for it to work in comfy:
https://huggingface.co/comfyanonymous/flux_RealismLora_converted_comfyui/blob/main/convert.py

**Comment by jaretburkett** [comment]
This appears to be an error in Comfy UI. Please report there. Or, if you are still having issues. Please ask [in the discord](https://discord.com/invite/nuR9zZ2nsh).
