### ISSUE TITLE
Training schnell lora oom

### ISSUE THREAD

**Issue by mno1337** [ostris/ai-toolkit#98]
No problem with the dev.1 one but with schnell i get this.
![image-142](https://github.com/user-attachments/assets/283006a0-9e22-4fa1-86ce-28ec64094bfd)

**Comment by jaretburkett** [comment]
Training with the schnell adapter gets tight on VRAM. It may oom if training a dim > 32 or if the gpu is also driving graphics. Let me know if this is not the case.
